Repository typelevel/Laika, pull requests merged in 2022-05, with the labels that each got.

#283 add canonicalLink attribute to page metadata
  core/shared/src/main/scala/laika/ast/DocumentMetadata.scala
  core/shared/src/main/scala/laika/config/ConfigDecoder.scala
  core/shared/src/main/scala/laika/config/ConfigEncoder.scala
  core/shared/src/test/scala/laika/config/ConfigCodecSpec.scala
  docs/src/03-preparing-content/03-theme-settings.md
  io/src/main/resources/laika/helium/templates/default.template.html
  io/src/test/scala/laika/helium/HeliumHTMLHeadSpec.scala
Labels: new feature

#282 use fs2 for TextInput, TextOutput, BinaryInput
  build.sbt
  io/src/main/scala/laika/helium/generate/MergedCSSGenerator.scala
  io/src/main/scala/laika/helium/generate/MergedStringInputs.scala
  io/src/main/scala/laika/io/config/ResourceLoader.scala
  io/src/main/scala/laika/io/model/Input.scala
  io/src/main/scala/laika/io/model/Output.scala
  io/src/main/scala/laika/io/ops/BinaryOutputOps.scala
  io/src/main/scala/laika/io/runtime/CopyRuntime.scala
  io/src/main/scala/laika/io/runtime/InputRuntime.scala
  io/src/main/scala/laika/io/runtime/OutputRuntime.scala
  io/src/main/scala/laika/io/runtime/RendererRuntime.scala
  io/src/main/scala/laika/io/runtime/VersionedLinkTargets.scala
  io/src/main/scala/laika/render/epub/ContainerWriter.scala
  io/src/main/scala/laika/render/epub/ZipWriter.scala
  io/src/test/scala/laika/io/FileIO.scala
  io/src/test/scala/laika/io/TreeRendererSpec.scala
  io/src/test/scala/laika/io/TreeTransformerSpec.scala
  io/src/test/scala/laika/io/helper/ResultExtractor.scala
  pdf/src/main/scala/laika/render/pdf/FopResourceResolver.scala
  preview/src/main/scala/laika/preview/SiteTransformer.scala
  project/Dependencies.scala
Labels: enhancement

#287 use fs2 for creating / scanning directories and for classpath resources
  io/src/main/scala/laika/io/model/Input.scala
  io/src/main/scala/laika/io/runtime/DirectoryScanner.scala
  io/src/main/scala/laika/io/runtime/RendererRuntime.scala
  io/src/test/scala/laika/io/FileIO.scala
  io/src/test/scala/laika/io/TreeRendererSpec.scala
Labels: enhancement

#286 Helium: automatically set canonical link for versioned pages via JavaScript
  core/shared/src/main/scala/laika/rewrite/Version.scala
  core/shared/src/test/scala/laika/config/ConfigCodecSpec.scala
  docs/src/03-preparing-content/01-directory-structure.md
  io/src/main/resources/laika/helium/js/versions.js
  io/src/main/scala/laika/helium/builder/HeliumDirectives.scala
  io/src/main/scala/laika/io/runtime/VersionInfoGenerator.scala
  io/src/test/scala/laika/helium/HeliumHTMLHeadSpec.scala
  io/src/test/scala/laika/helium/HeliumHTMLNavSpec.scala
  io/src/test/scala/laika/io/TreeRendererSpec.scala
Labels: new feature

#290 Deprecate API expecting java.io.File in favour of FilePath + introduce effectful FileFilter
  io/src/main/scala/laika/io/config/ResourceLoader.scala
  io/src/main/scala/laika/io/descriptor/InputDescriptor.scala
  io/src/main/scala/laika/io/descriptor/ParserDescriptor.scala
  io/src/main/scala/laika/io/descriptor/RendererDescriptor.scala
  io/src/main/scala/laika/io/model/FilePath.scala
  io/src/main/scala/laika/io/model/Input.scala
  io/src/main/scala/laika/io/model/Output.scala
  io/src/main/scala/laika/io/ops/BinaryOutputOps.scala
  io/src/main/scala/laika/io/ops/InputOps.scala
  io/src/main/scala/laika/io/ops/TextOutputOps.scala
  io/src/main/scala/laika/io/runtime/DirectoryScanner.scala
  io/src/main/scala/laika/io/runtime/ParserRuntime.scala
  io/src/main/scala/laika/io/runtime/RendererRuntime.scala
  io/src/main/scala/laika/io/runtime/TransformerRuntime.scala
  io/src/main/scala/laika/io/runtime/TreeResultBuilder.scala
  io/src/main/scala/laika/io/runtime/VersionedLinkTargets.scala
  io/src/main/scala/laika/render/epub/ContainerWriter.scala
  io/src/main/scala/laika/theme/config/Font.scala
  io/src/test/scala/laika/ast/ConfigSpec.scala
  io/src/test/scala/laika/directive/std/IncludeDirectiveSpec.scala
  io/src/test/scala/laika/io/FileIO.scala
  io/src/test/scala/laika/io/TreeParserFileIOSpec.scala
  io/src/test/scala/laika/io/TreeRendererSpec.scala
  io/src/test/scala/laika/io/TreeTransformerSpec.scala
  io/src/test/scala/laika/io/helper/InputBuilder.scala
  io/src/test/scala/laika/io/model/FilePathSpec.scala
  io/src/test/scala/laika/render/epub/XHTMLRendererSpec.scala
  pdf/src/main/scala/laika/render/pdf/FopFactoryBuilder.scala
  pdf/src/test/scala/laika/render/PDFRendererSpec.scala
  preview/src/main/scala/laika/preview/ServerBuilder.scala
  preview/src/main/scala/laika/preview/SiteTransformer.scala
  preview/src/main/scala/laika/preview/SourceChangeWatcher.scala
  preview/src/main/scala/laika/preview/StaticFileScanner.scala
  sbt/src/main/scala/laika/sbt/Settings.scala
  sbt/src/main/scala/laika/sbt/Tasks.scala
Labels: enhancement

#295 mention Dart syntax highlight for next release
  docs/src/01-about-laika/01-features.md
  docs/src/03-preparing-content/05-syntax-highlighting.md
Labels: documentation

#291 add methods for passing an fs2 Stream to InputTreeBuilder
  io/src/main/scala/laika/io/model/Input.scala
  io/src/test/scala/laika/io/TreeParserFileIOSpec.scala
Labels: new feature

#292 add InputTreeBuilder.describe + report missing directories
  io/src/main/scala/laika/io/descriptor/InputDescriptor.scala
  io/src/main/scala/laika/io/descriptor/ParserDescriptor.scala
  io/src/main/scala/laika/io/model/Input.scala
  io/src/main/scala/laika/io/runtime/ParserRuntime.scala
  io/src/test/scala/laika/io/TreeTransformerSpec.scala
Labels: enhancement

#298 refactor internal use of PathTranslator
  core/shared/src/main/scala/laika/ast/Cursor.scala
  core/shared/src/main/scala/laika/ast/documents.scala
  core/shared/src/main/scala/laika/directive/std/HTMLHeadDirectives.scala
  core/shared/src/main/scala/laika/rewrite/TemplateRewriter.scala
  core/shared/src/main/scala/laika/rewrite/nav/PathTranslator.scala
  core/shared/src/test/scala/laika/directive/std/HTMLHeadDirectiveSpec.scala
  core/shared/src/test/scala/laika/directive/std/NavigationDirectiveSpec.scala
  core/shared/src/test/scala/laika/directive/std/RewriteSetup.scala
  core/shared/src/test/scala/laika/render/HTMLRendererSpec.scala
  core/shared/src/test/scala/laika/rewrite/PathTranslatorSpec.scala
  core/shared/src/test/scala/laika/rst/std/StandardBlockDirectivesSpec.scala
  io/src/main/scala/laika/helium/builder/HeliumDirectives.scala
  io/src/main/scala/laika/io/model/RenderedTree.scala
  io/src/main/scala/laika/io/runtime/RendererRuntime.scala
  io/src/test/scala/laika/ast/ConfigSpec.scala
  io/src/test/scala/laika/directive/std/IncludeDirectiveSpec.scala
  io/src/test/scala/laika/io/TreeParserSpec.scala
  io/src/test/scala/laika/io/TreeRendererSpec.scala
  io/src/test/scala/laika/io/TreeTransformerSpec.scala
  io/src/test/scala/laika/io/helper/RenderedTreeAssertions.scala
  io/src/test/scala/laika/render/epub/InputTreeBuilder.scala
  io/src/test/scala/laika/render/epub/XHTMLRendererSpec.scala
  io/src/test/scala/laika/render/fo/XSLFORendererSpec.scala
  pdf/src/main/scala/laika/render/pdf/FOConcatenation.scala
  pdf/src/test/scala/laika/render/FOConcatenationSpec.scala
Labels: enhancement
