Repository typelevel/Laika, pull requests merged in 2023-05, with the labels that each got.

#418 update cats-effect, fs2, http4s
  project/Dependencies.scala
Labels: dependencies

#415 use no-op PathTranslator when transforming single input string
  core/shared/src/main/scala/laika/api/Renderer.scala
  core/shared/src/main/scala/laika/rewrite/nav/PathTranslator.scala
  core/shared/src/test/scala/laika/api/TransformAPISpec.scala
  core/shared/src/test/scala/laika/render/HTMLRendererSpec.scala
  io/src/test/scala/laika/io/TreeRendererSpec.scala
  io/src/test/scala/laika/io/TreeTransformerSpec.scala
  io/src/test/scala/laika/render/epub/InputTreeBuilder.scala
  io/src/test/scala/laika/render/fo/XSLFORendererSpec.scala
  io/src/test/scala/laika/theme/ThemeBundleSpec.scala
  pdf/src/test/scala/laika/render/FOConcatenationSpec.scala
Labels: bug

#417 Fix typo directive name in manual
  docs/src/07-reference/01-standard-directives.md
Labels: documentation

#416 Fix outdated code example.
  io/src/main/scala/laika/io/implicits.scala
Labels: documentation
