Repository typelevel/Laika, pull requests merged in 2023-06, with the labels that each got.

#421 avoid fs2 3.7.0 deprecation warnings about Files.apply
  io/src/main/scala/laika/io/config/ResourceLoader.scala
  io/src/main/scala/laika/io/model/BinaryInput.scala
  io/src/main/scala/laika/io/model/DirectoryInput.scala
  io/src/main/scala/laika/io/model/InputTreeBuilder.scala
  io/src/main/scala/laika/io/model/TextInput.scala
  io/src/main/scala/laika/io/model/TextOutput.scala
  io/src/main/scala/laika/io/runtime/DirectoryScanner.scala
  io/src/main/scala/laika/io/runtime/RendererRuntime.scala
  preview/src/main/scala/laika/preview/SourceChangeWatcher.scala
  preview/src/main/scala/laika/preview/StaticFileScanner.scala
Labels: enhancement

#422 add shell syntax highlighter
  core/shared/src/main/scala/laika/parse/code/SyntaxHighlighting.scala
  core/shared/src/main/scala/laika/parse/code/languages/ShellSyntax.scala
  core/shared/src/test/scala/laika/parse/code/languages/LanguageSpec.scala
  docs/src/01-about-laika/01-features.md
  docs/src/03-preparing-content/05-syntax-highlighting.md
Labels: new feature

#427 update Scala 3 to 3.3.0
  project/Dependencies.scala
Labels: dependencies

#428 update http4s to 0.23.21
  project/Dependencies.scala
Labels: dependencies

#434 Setup sbt-typelevel
  .github/workflows/ci.yml
  .github/workflows/clean.yml
  build.sbt
  core/shared/src/main/scala/laika/parse/css/CSSParsers.scala
  core/shared/src/main/scala/laika/rst/bundle/RstExtensionSupport.scala
  project/build.properties
  project/plugins.sbt
  sbt/src/sbt-test/site/ast/project/plugins.sbt
  sbt/src/sbt-test/site/choices/project/plugins.sbt
  sbt/src/sbt-test/site/config/project/plugins.sbt
  sbt/src/sbt-test/site/defaults/project/plugins.sbt
  sbt/src/sbt-test/site/directives/project/plugins.sbt
  sbt/src/sbt-test/site/docTypeMatcher/project/plugins.sbt
  sbt/src/sbt-test/site/epub/project/plugins.sbt
  sbt/src/sbt-test/site/excludeFilter/project/plugins.sbt
  sbt/src/sbt-test/site/generateASTandFO/project/plugins.sbt
  sbt/src/sbt-test/site/generateMultipleFormats/project/plugins.sbt
  sbt/src/sbt-test/site/github/project/plugins.sbt
  sbt/src/sbt-test/site/html/project/plugins.sbt
  sbt/src/sbt-test/site/includeAPI/project/plugins.sbt
  sbt/src/sbt-test/site/includeEPUB/project/plugins.sbt
  sbt/src/sbt-test/site/includePDF/project/plugins.sbt
  sbt/src/sbt-test/site/inputs/project/plugins.sbt
  sbt/src/sbt-test/site/packageSite/project/plugins.sbt
  sbt/src/sbt-test/site/pdf/project/plugins.sbt
  sbt/src/sbt-test/site/rawContent/project/plugins.sbt
  sbt/src/sbt-test/site/renderMessageLevel/project/plugins.sbt
  sbt/src/sbt-test/site/rewriteRules/project/plugins.sbt
  sbt/src/sbt-test/site/siteRenderers/project/plugins.sbt
  sbt/src/sbt-test/site/sourceDirectories/project/plugins.sbt
  sbt/src/sbt-test/site/strict/project/plugins.sbt
  sbt/src/sbt-test/site/targetAPI/project/plugins.sbt
  sbt/src/sbt-test/site/targetDir/project/plugins.sbt
  sbt/src/sbt-test/site/theme/project/plugins.sbt
  sbt/src/sbt-test/site/xslfo/project/plugins.sbt
Labels: build/CI

#435 Add `.jvmopts`
  .jvmopts
Labels: build/CI

#441 disable missing interpolator warnings
  build.sbt
Labels: build/CI

#442 avoid implicit numeric widening
  core/shared/src/main/scala/laika/ast/links.scala
  core/shared/src/main/scala/laika/directive/std/ImageDirectives.scala
  core/shared/src/main/scala/laika/parse/text/Characters.scala
  core/shared/src/main/scala/laika/parse/text/DelimitedText.scala
  core/shared/src/main/scala/laika/rst/std/StandardDirectiveParts.scala
  io/src/main/scala/laika/render/epub/ZipWriter.scala
Labels: enhancement

#443 remove unused parameters
  core/jvm/src/test/scala/laika/rst/ReStructuredTextToHTMLSpec.scala
  core/shared/src/main/scala/laika/ast/Cursor.scala
  core/shared/src/main/scala/laika/directive/api.scala
  core/shared/src/main/scala/laika/parse/code/common/CharLiteral.scala
  core/shared/src/main/scala/laika/parse/directive/DirectiveParsers.scala
  core/shared/src/main/scala/laika/parse/directive/TemplateParsers.scala
  core/shared/src/main/scala/laika/parse/hocon/ConfigResolver.scala
  core/shared/src/main/scala/laika/parse/text/Characters.scala
  core/shared/src/main/scala/laika/render/BaseFormatter.scala
  core/shared/src/main/scala/laika/render/FOFormatter.scala
  core/shared/src/main/scala/laika/render/FORenderer.scala
  core/shared/src/main/scala/laika/render/HTMLFormatter.scala
  core/shared/src/main/scala/laika/render/HTMLRenderer.scala
  core/shared/src/main/scala/laika/render/TagFormatter.scala
  core/shared/src/main/scala/laika/render/TextFormatter.scala
  core/shared/src/main/scala/laika/rewrite/ReferenceResolver.scala
  core/shared/src/main/scala/laika/rewrite/TemplateRewriter.scala
  core/shared/src/main/scala/laika/rewrite/link/DocumentTargets.scala
  core/shared/src/test/scala/laika/ast/sample/SampleTrees.scala
  core/shared/src/test/scala/laika/parse/ParserSpec.scala
  core/shared/src/test/scala/laika/rewrite/LinkValidatorSpec.scala
  core/shared/src/test/scala/laika/rewrite/PathTranslatorSpec.scala
  core/shared/src/test/scala/laika/rewrite/RewriteRulesSpec.scala
  io/src/main/scala/laika/render/epub/HtmlNavRenderer.scala
  io/src/main/scala/laika/render/epub/XHTMLRenderer.scala
  io/src/test/scala/laika/io/TreeRendererSpec.scala
  io/src/test/scala/laika/io/helper/RenderResult.scala
  io/src/test/scala/laika/render/epub/HTMLNavRendererSpec.scala
  preview/src/main/scala/laika/preview/ServerBuilder.scala
Labels: enhancement

#447 use explicit parentheses for passing tuples as sole argument
  core/shared/src/main/scala/laika/render/HTMLRenderer.scala
  core/shared/src/main/scala/laika/rst/std/StandardBlockDirectives.scala
  io/src/test/scala/laika/helium/HeliumLandingPageSpec.scala
Labels: enhancement

#444 fix broken boundary check in Parsers.lookAhead
  core/shared/src/main/scala/laika/parse/combinator/Parsers.scala
  core/shared/src/test/scala/laika/parse/ParserSpec.scala
Labels: bug

#450 remove unused private parameter defaults, vals and defs
  core/shared/src/main/scala/laika/ast/Cursor.scala
  core/shared/src/main/scala/laika/directive/std/StandardDirectives.scala
  core/shared/src/main/scala/laika/rst/InlineParsers.scala
  core/shared/src/test/scala/laika/directive/SpanDirectiveAPISpec.scala
  core/shared/src/test/scala/laika/directive/TemplateDirectiveAPISpec.scala
  core/shared/src/test/scala/laika/render/HTMLRendererSpec.scala
  io/src/main/scala/laika/helium/config/layout.scala
  io/src/main/scala/laika/render/epub/OPFRenderer.scala
  preview/src/main/scala/laika/preview/StaticFileScanner.scala
Labels: enhancement

#449 seal several traits in AST + parsers for exhaustive pattern matches
  core/shared/src/main/scala/laika/ast/Table.scala
  core/shared/src/main/scala/laika/ast/Target.scala
  core/shared/src/main/scala/laika/ast/base.scala
  core/shared/src/main/scala/laika/ast/links.scala
  core/shared/src/main/scala/laika/parse/markup/BlockParsers.scala
  core/shared/src/main/scala/laika/parse/text/DelimitedText.scala
Labels: enhancement

#445 ensure pattern matches are exhaustive
  core/shared/src/main/scala/laika/api/builder/OperationConfig.scala
  core/shared/src/main/scala/laika/ast/TreePosition.scala
  core/shared/src/main/scala/laika/ast/paths.scala
  core/shared/src/main/scala/laika/config/ConfigBuilder.scala
  core/shared/src/main/scala/laika/directive/std/LinkDirectives.scala
  core/shared/src/main/scala/laika/rst/TableParsers.scala
  core/shared/src/main/scala/laika/rst/std/StandardBlockDirectives.scala
  core/shared/src/main/scala/laika/rst/std/StandardDirectiveParts.scala
  core/shared/src/test/scala/laika/config/ParserBundleSpec.scala
  io/src/main/scala/laika/helium/builder/HeliumRenderOverrides.scala
  io/src/test/scala/laika/io/TreeParserSpec.scala
Labels: enhancement

#446 avoid compiler warnings for inferring Any
  core/shared/src/main/scala/laika/parse/css/CSSParsers.scala
  core/shared/src/main/scala/laika/parse/hocon/HoconParsers.scala
  core/shared/src/main/scala/laika/render/ASTRenderer.scala
  core/shared/src/main/scala/laika/rst/ExplicitBlockParsers.scala
  core/shared/src/main/scala/laika/rst/TableParsers.scala
  core/shared/src/test/scala/laika/rst/std/StandardBlockDirectivesSpec.scala
Labels: build/CI

#448 remove some constraints on F[_]
  io/src/main/scala/laika/factory/BinaryPostProcessor.scala
  io/src/main/scala/laika/io/api/BinaryTreeRenderer.scala
  io/src/main/scala/laika/io/model/BinaryInput.scala
  io/src/main/scala/laika/io/model/InputTreeBuilder.scala
  io/src/main/scala/laika/io/runtime/RendererRuntime.scala
  io/src/main/scala/laika/io/runtime/TransformerRuntime.scala
  io/src/main/scala/laika/render/epub/ContainerWriter.scala
  preview/src/main/scala/laika/preview/SiteTransformer.scala
Labels: enhancement
