Repository typelevel/Laika, pull requests merged in 2023-09, with the labels that each got.

#507 Fixed CSS for Code in Nav-Bars
  io/src/main/resources/laika/helium/css/nav.css
Labels: bug

#511 Helium: new configuration options for including script or style resources.
  build.sbt
  core/shared/src/main/scala/laika/config/LaikaKeys.scala
  core/shared/src/test/scala/laika/directive/std/HTMLHeadDirectiveSpec.scala
  docs/src/03-preparing-content/03-theme-settings.md
  docs/src/07-reference/01-standard-directives.md
  io/src/main/resources/laika/helium/templates/default.template.epub.xhtml
  io/src/main/resources/laika/helium/templates/includes/head.template.html
  io/src/main/scala/laika/helium/builder/HeliumDirectives.scala
  io/src/main/scala/laika/helium/builder/HeliumHeadDirectives.scala
  io/src/main/scala/laika/helium/builder/HeliumThemeBuilder.scala
  io/src/main/scala/laika/helium/config/includes.scala
  io/src/main/scala/laika/helium/config/layout.scala
  io/src/main/scala/laika/helium/config/settings.scala
  io/src/main/scala/laika/helium/generate/ConfigGenerator.scala
  io/src/main/scala/laika/helium/generate/LandingPageGenerator.scala
  io/src/main/scala/laika/theme/config/ScriptAttributes.scala
  io/src/main/scala/laika/theme/config/StyleAttributes.scala
  io/src/test/scala/laika/helium/HeliumEPUBHeadSpec.scala
  io/src/test/scala/laika/helium/HeliumHTMLHeadSpec.scala
  sbt/src/sbt-test/site/config/expected.html
  sbt/src/sbt-test/site/defaults/expected.html
  sbt/src/sbt-test/site/docTypeMatcher/expected.html
  sbt/src/sbt-test/site/excludeFilter/expected.html
  sbt/src/sbt-test/site/generateMultipleFormats/expected.html
  sbt/src/sbt-test/site/github/expected.html
  sbt/src/sbt-test/site/html/expected.html
  sbt/src/sbt-test/site/includeAPI/expected.html
  sbt/src/sbt-test/site/includeEPUB/expected.html
  sbt/src/sbt-test/site/includePDF/expected.html
  sbt/src/sbt-test/site/packageSite/expected.html
  sbt/src/sbt-test/site/rawContent/expected.html
  sbt/src/sbt-test/site/renderMessageLevel/expected.html
  sbt/src/sbt-test/site/rewriteRules/expected.html
  sbt/src/sbt-test/site/siteRenderers/expected.html
  sbt/src/sbt-test/site/sourceDirectories/expected.html
  sbt/src/sbt-test/site/sourceDirectories/expected2.html
  sbt/src/sbt-test/site/strict/expected.html
  sbt/src/sbt-test/site/targetAPI/expected.html
  sbt/src/sbt-test/site/targetDir/expected.html
  sbt/src/sbt-test/site/theme/expected.html
Labels: new feature

#512 introduce substitution variable `cursor.currentDocument.rawTitle`
  core/shared/src/main/scala/laika/rewrite/ReferenceResolver.scala
  docs/src/07-reference/02-substitution-variables.md
  io/src/main/resources/laika/helium/templates/includes/head.template.html
  io/src/test/scala/laika/helium/HeliumHTMLHeadSpec.scala
Labels: enhancement

#514 Markdown: allow URLs with nested parenthesis in links
  core/shared/src/main/scala/laika/markdown/InlineParsers.scala
  core/shared/src/test/scala/laika/markdown/InlineParsersSpec.scala
Labels: spec compliance

#513 preview server - render document AST under /ast path postfix
  build.sbt
  core/shared/src/main/scala/laika/render/ASTRenderer.scala
  docs/src/01-about-laika/01-features.md
  docs/src/02-running-laika/01-sbt-plugin.md
  docs/src/02-running-laika/02-library-api.md
  preview/src/main/scala/laika/preview/ASTPageTransformer.scala
  preview/src/main/scala/laika/preview/SiteTransformer.scala
  preview/src/test/scala/laika/preview/PreviewRouteSpec.scala
Labels: new feature

#515 link directives - properly support custom link text as documented
  core/shared/src/main/scala/laika/directive/DirectiveSupport.scala
  core/shared/src/test/scala/laika/directive/SpanDirectiveAPISpec.scala
  core/shared/src/test/scala/laika/directive/std/LinkDirectiveSpec.scala
  project/plugins.sbt
Labels: bug

#522 merge features from 0.19.4 for 1.x - minus all deprecations
  .scalafmt.conf
  core/jvm/src/test/resources/markdownTestSuite/Hard-wrapped paragraphs with list-like lines.html
  core/shared/src/main/scala/laika/ast/DocumentTreeBuilder.scala
  core/shared/src/main/scala/laika/config/LaikaKeys.scala
  core/shared/src/main/scala/laika/directive/DirectiveSupport.scala
  core/shared/src/main/scala/laika/directive/std/HTMLHeadDirectives.scala
  core/shared/src/main/scala/laika/directive/std/StandardDirectives.scala
  core/shared/src/main/scala/laika/format/Markdown.scala
  core/shared/src/main/scala/laika/markdown/InlineParsers.scala
  core/shared/src/main/scala/laika/render/ASTRenderer.scala
  core/shared/src/main/scala/laika/rewrite/ReferenceResolver.scala
  core/shared/src/test/scala/laika/directive/SpanDirectiveAPISpec.scala
  core/shared/src/test/scala/laika/directive/std/HTMLHeadDirectiveSpec.scala
  core/shared/src/test/scala/laika/directive/std/LinkDirectiveSpec.scala
  core/shared/src/test/scala/laika/markdown/InlineParsersSpec.scala
  core/shared/src/test/scala/laika/rst/std/StandardSpanDirectivesSpec.scala
  docs/src/01-about-laika/01-features.md
  docs/src/02-running-laika/01-sbt-plugin.md
  docs/src/02-running-laika/02-library-api.md
  docs/src/02-running-laika/03-configuration.md
  docs/src/03-preparing-content/03-theme-settings.md
  docs/src/07-reference/01-standard-directives.md
  docs/src/07-reference/02-substitution-variables.md
  io/src/main/resources/laika/helium/css/content.css
  io/src/main/resources/laika/helium/css/nav.css
  io/src/main/resources/laika/helium/templates/default.template.epub.xhtml
  io/src/main/resources/laika/helium/templates/includes/head.template.html
  io/src/main/resources/laika/helium/templates/landing.template.html
  io/src/main/scala/laika/helium/Helium.scala
  io/src/main/scala/laika/helium/builder/HeliumDirectives.scala
  io/src/main/scala/laika/helium/builder/HeliumHeadDirectives.scala
  io/src/main/scala/laika/helium/builder/HeliumInputBuilder.scala
  io/src/main/scala/laika/helium/builder/HeliumRenderOverrides.scala
  io/src/main/scala/laika/helium/builder/HeliumThemeBuilder.scala
  io/src/main/scala/laika/helium/builder/HeliumTreeProcessor.scala
  io/src/main/scala/laika/helium/config/HeliumDefaults.scala
  io/src/main/scala/laika/helium/config/includes.scala
  io/src/main/scala/laika/helium/config/layout.scala
  io/src/main/scala/laika/helium/config/settings.scala
  io/src/main/scala/laika/helium/generate/ConfigGenerator.scala
  io/src/main/scala/laika/helium/generate/LandingPageGenerator.scala
  io/src/main/scala/laika/helium/generate/MermaidInitializer.scala
  io/src/main/scala/laika/theme/config/ScriptAttributes.scala
  io/src/main/scala/laika/theme/config/StyleAttributes.scala
  io/src/test/scala/laika/helium/HeliumEPUBHeadSpec.scala
  io/src/test/scala/laika/helium/HeliumHTMLHeadSpec.scala
  io/src/test/scala/laika/helium/HeliumLandingPageSpec.scala
  io/src/test/scala/laika/helium/HeliumRenderOverridesSpec.scala
  io/src/test/scala/laika/io/ParserSetup.scala
  io/src/test/scala/laika/io/TreeParserSpec.scala
  io/src/test/scala/laika/io/TreeTransformerSpec.scala
  preview/src/main/scala/laika/preview/ASTPageTransformer.scala
  preview/src/main/scala/laika/preview/SiteTransformer.scala
  preview/src/test/scala/laika/preview/PreviewRouteSpec.scala
  project/Dependencies.scala
  project/build.properties
  project/plugins.sbt
  sbt/src/main/scala/laika/sbt/LaikaConfig.scala
  sbt/src/main/scala/laika/sbt/Tasks.scala
Labels: new feature

#518 introduce some deprecations to help with migrating to 1.x
  core/shared/src/main/scala/laika/ast/Cursor.scala
  core/shared/src/main/scala/laika/ast/DocumentTreeBuilder.scala
  core/shared/src/main/scala/laika/ast/documents.scala
  core/shared/src/main/scala/laika/directive/std/LinkDirectives.scala
  core/shared/src/main/scala/laika/rewrite/link/LinkConfig.scala
  core/shared/src/test/scala/laika/ast/DocumentTreeAPISpec.scala
  core/shared/src/test/scala/laika/ast/DocumentTreeBuilderSpec.scala
  core/shared/src/test/scala/laika/config/ConfigCodecSpec.scala
  core/shared/src/test/scala/laika/rewrite/RewriteRulesSpec.scala
  docs/src/02-running-laika/01-sbt-plugin.md
  docs/src/02-running-laika/02-library-api.md
  io/src/main/scala/laika/helium/config/settings.scala
  io/src/main/scala/laika/io/descriptor/TransformerDescriptor.scala
  io/src/main/scala/laika/io/runtime/TreeResultBuilder.scala
  io/src/test/scala/laika/io/TreeParserFileIOSpec.scala
  io/src/test/scala/laika/io/TreeParserSpec.scala
  io/src/test/scala/laika/io/TreeRendererSpec.scala
  sbt/src/main/scala/laika/sbt/LaikaConfig.scala
Labels: public APIs

#523 simplify and clean up Formatter APIs
  core/jvm/src/test/scala/laika/markdown/MarkdownToHTMLSpec.scala
  core/jvm/src/test/scala/laika/rst/ReStructuredTextToHTMLSpec.scala
  core/shared/src/main/scala/laika/api/Renderer.scala
  core/shared/src/main/scala/laika/api/builder/OperationConfig.scala
  core/shared/src/main/scala/laika/ast/base.scala
  core/shared/src/main/scala/laika/factory/RenderFormat.scala
  core/shared/src/main/scala/laika/format/AST.scala
  core/shared/src/main/scala/laika/format/HTML.scala
  core/shared/src/main/scala/laika/format/XSLFO.scala
  core/shared/src/main/scala/laika/markdown/bundle/HTMLRenderer.scala
  core/shared/src/main/scala/laika/render/ASTRenderer.scala
  core/shared/src/main/scala/laika/render/BaseFormatter.scala
  core/shared/src/main/scala/laika/render/FOFormatter.scala
  core/shared/src/main/scala/laika/render/FORenderer.scala
  core/shared/src/main/scala/laika/render/Formatter.scala
  core/shared/src/main/scala/laika/render/HTMLFormatter.scala
  core/shared/src/main/scala/laika/render/HTMLRenderer.scala
  core/shared/src/main/scala/laika/render/TagFormatter.scala
  core/shared/src/main/scala/laika/render/TextFormatter.scala
  core/shared/src/main/scala/laika/rst/ast/elements.scala
  core/shared/src/main/scala/laika/rst/bundle/ExtendedHTMLRenderer.scala
  core/shared/src/test/scala/laika/render/HTMLRendererSpec.scala
  docs/src/04-customizing-laika/06-overriding-renderers.md
  docs/src/05-extending-laika/07-new-markup-output-formats.md
  docs/src/07-reference/07-migration-guide.md
  io/src/main/scala/laika/format/EPUB.scala
  io/src/main/scala/laika/helium/builder/HeliumRenderOverrides.scala
  io/src/main/scala/laika/render/epub/XHTMLRenderer.scala
  io/src/test/scala/laika/format/TestRenderResultProcessor.scala
  io/src/test/scala/laika/helium/HeliumDownloadPageSpec.scala
  io/src/test/scala/laika/helium/HeliumRenderOverridesSpec.scala
  io/src/test/scala/laika/io/TreeRendererSpec.scala
  pdf/src/main/scala/laika/format/PDF.scala
  pdf/src/test/scala/laika/render/PDFNavigationSpec.scala
  sbt/src/main/scala/laika/sbt/ExtensionBundles.scala
  sbt/src/sbt-test/site/siteRenderers/build.sbt
Labels: public APIs

#524 fix perfomance regression in preview server bootstrapping
  build.sbt
  preview/src/main/scala/laika/preview/ASTPageTransformer.scala
  preview/src/main/scala/laika/preview/RouteBuilder.scala
  preview/src/main/scala/laika/preview/SiteTransformer.scala
Labels: performance

#525 tweak MarkupFormat API to encourage public declarations for top-level parsers
  .github/workflows/ci.yml
  core/shared/src/main/scala/laika/factory/MarkupFormat.scala
  core/shared/src/main/scala/laika/format/Markdown.scala
  core/shared/src/main/scala/laika/format/ReStructuredText.scala
  core/shared/src/main/scala/laika/markdown/BlockParsers.scala
  core/shared/src/main/scala/laika/markdown/InlineParsers.scala
  core/shared/src/main/scala/laika/markdown/ListParsers.scala
  core/shared/src/main/scala/laika/parse/markup/RootParser.scala
  core/shared/src/main/scala/laika/rst/BlockParsers.scala
  core/shared/src/main/scala/laika/rst/InlineParsers.scala
  core/shared/src/main/scala/laika/rst/ListParsers.scala
  core/shared/src/main/scala/laika/rst/TableParsers.scala
  core/shared/src/test/scala/laika/config/OperationConfigSpec.scala
  core/shared/src/test/scala/laika/config/ParserBundleSpec.scala
  core/shared/src/test/scala/laika/parse/markup/RootParserProvider.scala
  docs/src/05-extending-laika/07-new-markup-output-formats.md
  project/plugins.sbt
Labels: public APIs

#526 reduce use of compound suffixes - adjust Path.suffix to split at last dot
  core/shared/src/main/scala/laika/ast/documents.scala
  core/shared/src/main/scala/laika/ast/paths.scala
  core/shared/src/main/scala/laika/bundle/DocumentTypeMatcher.scala
  core/shared/src/main/scala/laika/rewrite/DefaultTemplatePath.scala
  core/shared/src/main/scala/laika/rewrite/nav/TargetFormats.scala
  core/shared/src/test/scala/laika/ast/PathAPISpec.scala
  docs/src/03-preparing-content/04-ebooks.md
  io/src/main/scala/laika/format/EPUB.scala
  io/src/main/scala/laika/helium/builder/HeliumHeadDirectives.scala
  io/src/main/scala/laika/helium/builder/HeliumInputBuilder.scala
  io/src/main/scala/laika/helium/builder/HeliumTreeProcessor.scala
  io/src/main/scala/laika/helium/generate/CSSVarGenerator.scala
  io/src/main/scala/laika/io/model/BinaryInput.scala
  io/src/main/scala/laika/io/model/InputTreeBuilder.scala
  io/src/main/scala/laika/io/model/ParsedTree.scala
  io/src/main/scala/laika/io/runtime/ParserRuntime.scala
  io/src/main/scala/laika/io/runtime/RendererRuntime.scala
  io/src/main/scala/laika/render/epub/MimeTypes.scala
  io/src/main/scala/laika/render/epub/NavigationBuilder.scala
  io/src/main/scala/laika/render/epub/OPFRenderer.scala
  io/src/test/scala/laika/helium/HeliumDownloadPageSpec.scala
  io/src/test/scala/laika/helium/HeliumEPUBCSSSpec.scala
  io/src/test/scala/laika/helium/HeliumEPUBHeadSpec.scala
  io/src/test/scala/laika/helium/HeliumEPUBTocPageSpec.scala
  io/src/test/scala/laika/helium/HeliumHTMLHeadSpec.scala
  io/src/test/scala/laika/helium/HeliumLandingPageSpec.scala
  io/src/test/scala/laika/helium/HeliumSiteCSSSpec.scala
  io/src/test/scala/laika/helium/HeliumTocPageSpec.scala
  io/src/test/scala/laika/io/TreeParserFileIOSpec.scala
  io/src/test/scala/laika/io/TreeParserSpec.scala
  io/src/test/scala/laika/io/TreeRendererSpec.scala
  io/src/test/scala/laika/render/epub/HTMLNavRendererSpec.scala
  io/src/test/scala/laika/render/epub/NCXRendererSpec.scala
  io/src/test/scala/laika/render/epub/OPFRendererSpec.scala
  io/src/test/scala/laika/render/fo/TestTheme.scala
  preview/src/main/scala/laika/preview/SiteTransformer.scala
  sbt/src/sbt-test/site/config/expected.html
  sbt/src/sbt-test/site/defaults/expected.html
  sbt/src/sbt-test/site/docTypeMatcher/expected.html
  sbt/src/sbt-test/site/excludeFilter/expected.html
  sbt/src/sbt-test/site/generateMultipleFormats/expected.html
  sbt/src/sbt-test/site/github/expected.html
  sbt/src/sbt-test/site/html/expected.html
  sbt/src/sbt-test/site/includeAPI/expected.html
  sbt/src/sbt-test/site/includeEPUB/expected.html
  sbt/src/sbt-test/site/includePDF/expected.html
  sbt/src/sbt-test/site/packageSite/expected.html
  sbt/src/sbt-test/site/rawContent/expected.html
  sbt/src/sbt-test/site/renderMessageLevel/expected.html
  sbt/src/sbt-test/site/rewriteRules/expected.html
  sbt/src/sbt-test/site/siteRenderers/expected.html
  sbt/src/sbt-test/site/sourceDirectories/expected.html
  sbt/src/sbt-test/site/sourceDirectories/expected2.html
  sbt/src/sbt-test/site/strict/expected.html
  sbt/src/sbt-test/site/targetAPI/expected.html
  sbt/src/sbt-test/site/targetDir/expected.html
  sbt/src/sbt-test/site/theme/expected.html
Labels: bug, enhancement

#527 update fs2 to 3.9.2
  project/Dependencies.scala
Labels: dependencies

#532 bring fix for perfomance regression in preview server to 1.x
  preview/src/main/scala/laika/preview/ASTPageTransformer.scala
  preview/src/main/scala/laika/preview/RouteBuilder.scala
  preview/src/main/scala/laika/preview/SiteTransformer.scala
Labels: enhancement

#535 set up unidoc publishing
  .github/workflows/ci.yml
  build.sbt
  docs/api/index.html
  project/ScaladocCleanup.scala
Labels: documentation

#538 fix overeager validation of link target formats
  core/shared/src/main/scala/laika/internal/link/LinkValidator.scala
  io/src/test/scala/laika/helium/HeliumHTMLHeadSpec.scala
Labels: bug

#540 apply workaround for scaladoc bugs only for Scala 2.12
  build.sbt
  project/ScaladocCleanup.scala
Labels: enhancement

#541 global link definitions should use case-insensitive matching logic
  core/shared/src/main/scala/laika/internal/link/DocumentTargets.scala
  core/shared/src/test/scala/laika/markdown/InlineParsersSpec.scala
  core/shared/src/test/scala/laika/rewrite/RewriteRulesSpec.scala
Labels: enhancement

#542 migrate to Laika 1.x for the manual build
  README.md
  build.sbt
  docs/src/03-preparing-content/03-theme-settings.md
  docs/src/img/cover/e-book-cover-lib-1.x.png
  docs/src/img/cover/e-book-cover-sbt-1.x.png
  docs/src/img/pdf/e-book-cover-lib-1.x.png
  docs/src/img/pdf/e-book-cover-sbt-1.x.png
  docs/src/laika/versionInfo.json
  docs/src/olderVersions/README.md
  project/ManualBundle.scala
  project/ManualSettings.scala
  project/plugins.sbt
Labels: documentation
